server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: 5000ms
        max-idle: 30
        min-idle: 15
        time-between-eviction-runs: 60s
        min-evictable-idle-time: 120000
        max-evictable-idle-time: 300000
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug